### ISSUE TITLE
Rating filter

### ISSUE THREAD

**Issue by nlemoine** [luukdv/whatmovie#1]
Nice app! 

Would be nice to have a rating filter (2+, 3+, 4+, etc.).

**Comment by luukdv** [comment]
Thanks!

Bit of a late response, have been working on a rewrite of the code. I'm trying to keep the app as simple as possible (just 'hitting the button'), but this sounds nice. What do you think the default should be?

**Comment by nlemoine** [comment]
Thanks for your considering the request. 

Starting from 5: 5+, 6+, 7+, 8+, 9+ in a form of a list of radio inputs or a select dropdown. What do you think ?

**Comment by luukdv** [comment]
Finally finished this. Decided to go with a slider, which took some time to build.

**Comment by nlemoine** [comment]
This is great work! Thanks again for adding the feature.
